#!/bin/bash
# SessionComplete hook — logs a summary after every Claude Code session
# Wired in settings.json under hooks.SessionComplete

LOG_DIR=".claude/logs"
mkdir -p "$LOG_DIR"

TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_FILE="$LOG_DIR/session-$TIMESTAMP.md"

# Get list of files changed this session via git
CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null || echo "git not available")
UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null || echo "")

cat > "$LOG_FILE" << EOF
# Session Log — $TIMESTAMP

## Changed files
$CHANGED_FILES

## New files
$UNTRACKED

## Git status
$(git status --short 2>/dev/null || echo "git not available")

---
*Generated by session-summary hook*
EOF

echo "📝 Session log written to $LOG_FILE"
exit 0
